rootProject.name = "itmo-web-labs"
include(":common")
include(":jsp")
include(":lab3")
include(":lab4")
include(":modules:utility")
include(":modules:graph")
include(":modules:db")
include(":modules:db:string")
include(":modules:db:jakarta")
