version: "3.8"

name: "web-labs"

services:
  wildfly:
    build: ./wildfly/
    image: wildfly:29.0.1.Final-alpine
    ports:
      - "9990:8080"
      - "9989:9989"
      - "9991:9990"

  h2:
    build: ./h2/
    image: h2:2.2.224-alpine
    ports:
      - "9992:8082"
      - "9993:9092"